# Use this file in order to run a local/dev copy of the server.
# Rename it to docker-compose.override.yml
version: "3.3"
services:
  db:
    restart: "no"
    logging:
      driver: "json-file"
    volumes:
      - /tmp/minetest/db:/var/lib/postgresql/data
  game:
    restart: "no"
    logging:
      driver: "json-file"
    image: ghcr.io/ronoaldo/mercurio:beta
    ports:
      - "30000:30000/udp"
      - "30000:30000/tcp"
    volumes:
      - /tmp/minetest/world:/var/lib/mercurio
  mapserver:
    restart: "no"