services:
  db:
    restart: "no"
    ports:
      - "5432:5432/tcp"
  game:
    image: ghcr.io/ronoaldo/mercurio:beta
    restart: "no"
    ports:
      - "30000:30000/udp"
      - "30000:30000/tcp"
    environment:
      - NO_LOOP=true
  discordmt:
    restart: "no"

