apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mercurio
  name: mercurio

spec:
  containers:
  - name: db
    image: postgres:13
    volumeMounts:
      - mountPath: /var/lib/postgresql/data
        name: db-data
    args:
      - "-c"
      - "shared_buffers=1024MB"
    envFrom:
      - configMapRef:
          name: env

  - name: game
    image: ghcr.io/ronoaldo/mercurio:main
    imagePullPolicy: IfNotPresent
    envFrom:
      - configMapRef:
          name: env
    volumeMounts:
      - mountPath: /var/lib/mercurio
        name: mercurio-world
    ports:
      - containerPort: 30000
        hostPort: 30000
        protocol: UDP
      - containerPort: 30000
        hostPort: 30000
        protocol: UDP
    securityContext:
      runAsUser: 30000
      runAsGroup: 30000
      fsGroup: 30000

#  TODO(ronoaldo): re-enable this once the file permission issues are fixed.
#  - name: mapserver
#    image: minetestmapserver/mapserver:4.3.2
#    volumeMounts:
#      - mountPath: /minetest
#        name: mercurio-world
  
  volumes:
    - name: db-data
      hostPath:
        path: ./.minetest/db
        type: Directory
    - name: mercurio-world
      hostPath:
        path: ./.minetest/world
        type: Directory
        securityContext:
          fsGroup: 30000
