name = steampunk_blimp
depends = airutils
optional_depends = rp_crafting, cannons, default, mcl_core, mcl_tnt
author = apercy
description = Adds a steampunk blimp
title = Steampunk Blimp
release = 36898

