name = areas
optional_depends = playerfactions
min_minetest_version = 5.0
author = ShadowNinja
release = 34950
title = Areas
description = Areas is a advanced area protection mod based on node_ownership.

