name: Test docker image builds for pull-requests

on:
  push:
    branches-ignore: ['main']
  pull_request:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test-the-server:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build docker image
        run: docker-compose build
      
      - name: Run tests and export mods
        run: make test
